<!DOCTYPE html>
<!--[if lt IE 7]>  <html class="ie ie6 lt-ie7"> <![endif]-->
<!--[if IE 7]>     <html class="ie ie7"> <![endif]-->
<!--[if IE 8]>     <html class="ie ie8"> <![endif]-->
<!--[if IE 9]>     <html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]>  <html class="ie gt-ie9" <![endif]-->
<!--[if !IE]><!--><html><!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <title><?= 'STU Online Judge' ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="/asset/components/Flat-UI/css/bootstrap.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="/asset/components/Flat-UI/css/flat-ui.css" rel="stylesheet">
    <link rel="shortcut icon" href="images/favicon.ico">

    <link href="/asset/style.css" rel="stylesheet">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->
  </head>
  <body>