<?= $this->partial('/common/header.phtml', $this) ?>
<?= $this->partial('/common/navbar.phtml', $this) ?>
<div class="container">
    <div class="login">
        <div class="login-screen">
            <div class="login-icon">
                <img src="/asset/components/Flat-UI/images/illustrations/colors.png" alt="" />
                <h4>歡迎使用 <small><?= PROJECT_NAME ?></small></h4>
            </div>

            <div class="login-form">
                <div class="control-group">
                    <input class="login-field" id="login-name" type="text" value="" placeholder="請輸入帳號" />
                    <label class="login-field-icon fui-man-16" for="login-name"></label>
                </div>

                <div class="control-group">
                    <input class="login-field" id="login-pass" type="password" value="" placeholder="密碼" />
                    <label class="login-field-icon fui-lock-16" for="login-pass"></label>
                </div>

                <a class="btn btn-primary btn-large btn-block" href="#">Login</a>
                <a class="login-link" href="#">Lost your password?</a>
            </div>
        </div>
    </div>
</div>
<?= $this->partial('/common/footer.phtml', $this) ?>
