<?= $this->partial('/common/header.phtml', $this) ?>
<?= $this->partial('/common/navbar.phtml', $this) ?>
<div class="container">
    <h1><?= $this->problem->title ?></h1>
    <p><?= $this->problem->content ?></p>
    <pre><?= $this->problem->source_code ?></pre>
    <h4>輸入</h4>
    <pre><?= $this->problem->input ?></pre>
    <h4>輸出</h4>
    <pre><?= $this->problem->output ?></pre>
    <a class="btn" href="/problem/solve/<?= $this->problem->id ?>">解題</a>
</div>
<?= $this->partial('/common/footer.phtml', $this) ?>
