<?= $this->partial('/common/header.phtml', $this) ?>
<?= $this->partial('/common/navbar.phtml', $this) ?>
<div class="container">
    <h1>#<?= $this->problem->id . ': ' . $this->escape($this->problem->title) ?></h1>
    <p><?= $this->escape($this->problem->content) ?></p>
    <form action="/problem/solve/<?= $this->problem->id ?>" method="post">
        <div class="editor-container">
            <div id="editor">// 在此貼上你的程式碼</div>
        </div><!-- /.edit-container -->
        <div class="form-actions">
            <button type="submit" class="btn">送出程式碼</button>
        </div>
    </form>
</div>
<script src="http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
var editor = ace.edit("editor");
editor.setTheme("ace/theme/solarized_light");
editor.getSession().setMode("ace/mode/java");
editor.getSession().setUseSoftTabs(true);
editor.getSession().setAutoScrollEditorIntoView(true);
</script>
<?= $this->partial('/common/footer.phtml', $this) ?>
