<?= $this->partial('/common/header.phtml', $this) ?>
<?= $this->partial('/common/navbar.phtml', $this) ?>
<div class="container">
    <h1>#<?= $this->problem->id . ': ' . $this->escape($this->problem->title) ?></h1>
    <p><?= nl2br($this->escape($this->problem->content)) ?></p>
    <form action="/problem/solve/<?= $this->problem->id ?>" method="post">
        <input name="sToken" type="hidden" value="<?= $this->escape($this->sToken) ?>">
        <select class="language-chooser" name="language">
            <?php foreach ($this->languages as $lang_id => $lang): ?>
            <option value="<?= $lang_id ?>" data-lang="<?= $lang['slug'] ?>"><?= $lang['name'] ?></option>
            <?php endforeach; ?>
        </select>
        <div class="editor-container">
            <div class="editor" id="source_code">/* 在此貼上你的程式碼 */
        </div>
            <textarea id="source_code-textarea" name="source_code"></textarea>
        </div><!-- /.edit-container -->
        <div class="form-actions">
            <button type="submit" class="btn">送出程式碼</button>
        </div>
    </form>
</div>
<script src="http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
var editor = ace.edit("source_code");
var textarea = document.getElementById('source_code-textarea');
editor.setTheme("ace/theme/solarized_light");
editor.getSession().setMode("ace/mode/java");
editor.getSession().setUseSoftTabs(true);
editor.getSession().on('change', function(){
    textarea.value = editor.getSession().getValue();
});

$('.language-chooser').change(function(){
    var lang = $(this).children('option:selected').data('lang');
    editor.getSession().setMode("ace/mode/" + lang);
});
</script>
<?= $this->partial('/common/footer.phtml', $this) ?>
