<?= $this->partial('/common/header.phtml', $this) ?>
<?= $this->partial('/common/navbar.phtml', $this) ?>
<div class="container">
    <h1>解題動態</h1>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>提交者</th>
                <th>題目</th>
                <th>評測結果</th>
                <th>時間</th>
                <th>程式碼</th>
                <th>時間</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->solutions as $solution): ?>
        <tr>
            <td><?= $solution->id ?></td>
            <td><a href="/users/<?= $solution->user->account ?>"><?= $solution->user->name ?></a></td>
            <td><a href="/problem/browse/<?= $solution->problem->id ?>"><?= $solution->problem->title ?></a></td>
            <td><?= $solution->getStatusLabel() ?>
                <?php if ($solution->isWA()): ?>
                <a href="/solution/browse/<?= $solution->id ?>">詳細</a>
                <?php endif; ?>
            </td>
            <td><?= $solution->getExecuteTimeText() ?></a></td>
            <td><?= $solution->getLanguageName() ?></a></td>
            <td><?= date('Y-m-d H:i:s', $solution->created_at) ?></a></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?= $this->partial('/common/footer.phtml', $this) ?>
